version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks: 
      - prometheus
    links:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules
    command:
      - --web.enable-lifecycle
    networks: 
      - prometheus
    ports:
      - 9090:9090
    links:
      - alertmanager
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./config/alertmanager:/etc/alertmanager
    networks: 
      - prometheus
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    restart: always

networks:
  prometheus:
    driver: bridge
