global:
  scrape_interval: 15s
  external_labels:
    monitor: "docker-monitor"
alerting:
  alertmanagers:
   - static_configs:
     - targets: ["alertmanager:9093"]

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node_exporter_server
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.1.162:9100"]

  - job_name: container_server
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.1.162:9100"]
  
  - job_name: pm2_server
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.1.200:9100"]